### ISSUE TITLE
Implement Cloudinary Video/Image Upload Widget

### ISSUE THREAD

**Issue by MekhiTudor** [TEAM-3PM/CopCheck#37]
### Description
Integrate Cloudinary's upload widget into the frontend of the application, enabling users to upload images and videos seamlessly.

### Acceptance Criteria
- The Cloudinary upload widget is fully functional and allows users to upload images and videos.
- The uploaded media references are saved and displayed appropriately.
- The application loads the widget script correctly on startup.

### Tasks

- [x] **Install Cloudinary Packages**
  - Run the following command to install the necessary packages:
    ```bash
    npm i @cloudinary/url-gen @cloudinary/react
    ```
  - Verify that the packages are correctly installed in the project.

- [x] **Add Upload Widget Script**
  - Open the `index.html` file located in the `public` directory.
  - Insert the script tag within the `<head>` section to load the Cloudinary upload widget.
  - Confirm that the script is correctly referenced and loads when the application starts.

- [x] **Create UploadWidget Component**
  - Create a new file named `UploadWidget.js` in the components directory.
  - Implement the `UploadWidget` component to:
    - Initialize the Cloudinary widget.
    - Handle image/video uploads.
    - Save the uploaded media references (URLs) in the component state.

- [ ] **Integrate UploadWidget into App.js**
  - Open `App.js` in the root of your `src` directory.
  - Import the `UploadWidget` component.
  - Insert the `UploadWidget` component in the render method, wherever appropriate.

- [x] **Configure Cloudinary Cloud Name**
  - In `UploadWidget.js`, ensure the `cloudName` variable is set to the Cloudinary cloud name retrieved from your Cloudinary account.

- [x] **Test Functionality**
  - Run the application locally to ensure the upload widget loads correctly.
  - Test the upload functionality with various image and video formats to verify that uploads succeed and references are correctly saved.

- [ ] **Documentation**
  - Update project documentation with steps for setting up and using the Cloudinary upload widget.
  - Include any necessary API keys or environment variable setup in the documentation.

### Additional Notes
- Consider implementing error handling for upload failures and displaying user-friendly messages.
- Review Cloudinary's documentation for advanced configuration options and additional features.
